#!/bin/sh 

# while-menu-dialog: a menu driven system information program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "System Information" \
    --title "Menu" \
    --clear \
    --cancel-label "Cancel" \
    --menu "Please select:" $HEIGHT $WIDTH 5 \
    "1" "CPU INFO" \
    "2" "MEMORY INFO" \
    "3" "NET INFO" \
    "4" "FILE BROWSER"\
    2>&1 1>&3
  )
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      result=$(sysctl hw.model hw.machine hw.ncpu)
      #result=$(dmesg | grep -i cpu)
      display_result "CPU INFO"
      ;;
    2 )
      result=$(sysctl hw | egrep 'hw.(phys|user|real)')
      #result=$(df -h)
      display_result "MEMORY INFO"
      ;;
    3 )
      result=$(ifconfig)
      display_result "NET INFO"
      ;;

    4 )
      #result=$(ls -al)	
      #display_result "FILE BROSWER"
      dialog --title "Pick one file" --fselect /root/ 7 40
      ;;
  esac
done
