#!/bin/sh
# top 5
find ${PWD} -type f -print0 | du --files0-from=- -bc | sort -n -r | head -n 6 | tail -n 5 | awk '{cnt++} {print cnt ": " $1 " " $2}'
# total directory except ./
find ${PWD} -mindepth 1 -type d | wc -l | awk '{print "Dir num: " $1}'
# total file num + 1
find ${PWD} -type f | wc -l | awk '{print "File num: " $1}'
# total file size
find ${PWD} -type f -print0 | du --files0-from=- -bc | tail -n 1 | awk '{print "Total: " $1}'
